/// Every command in `lib.rs`'s `generate_handler!`. Listing them makes the
/// Tauri ACL govern app commands, so a webview only reaches the commands its
/// capability in `capabilities/` grants. Keep this in sync with the handler;
/// `tests/tauri-config.test.mjs` checks both lists and the main capability.
const APP_COMMANDS: &[&str] = &[
    "health",
    "perf_snapshot_v2",
    "record_frontend_error",
    "diagnostics_path",
    "restart_app",
    "secret_storage_status",
    "request_desktop_hide",
    "request_desktop_quit",
    "set_sidebar_toggle_enabled",
    "set_workspace_editor_dirty",
    "complete_workspace_editor_leave",
    "api_base_url",
    "api_token",
    "refresh_provider_models",
    "mobile_tailscale_status",
    "configure_mobile_tailscale",
    "disable_mobile_tailscale",
    "mobile_lan_status",
    "set_mobile_lan_enabled",
    "user_state_get",
    "user_state_set",
    "user_state_delete",
    "user_sessions_get",
    "user_sessions_manifest_get",
    "user_session_messages_page",
    "user_session_snapshot",
    "user_chat_search",
    "user_sessions_set",
    "user_sessions_apply_delta",
    "user_sessions_apply_ops",
    "user_sessions_delete",
    "user_state_import_legacy",
    "export_milim_backup",
    "inspect_milim_backup",
    "restore_milim_backup",
    "quit_after_user_state_flush",
    "user_data_path",
    "pick_attachment_files",
    "read_workspace_attachment_file",
    "list_workspace_files",
    "list_workspace_directory",
    "read_workspace_text_file",
    "write_workspace_text_file",
    "save_artifact_file",
    "preview_artifact_file",
    "artifact_file_status",
    "open_artifact_location",
    "list_workspace_launchers",
    "open_workspace_launcher",
    "open_external_url",
    "discover_harness_imports",
    "get_update_platform",
    "take_update_recovery_error",
    "download_update_file",
    "extract_app_zip",
    "apply_update",
    "set_active_preview_target",
    "preview_picker_start",
    "preview_picker_take",
    "preview_picker_cancel",
    "preview_webview_navigate",
    "preview_webview_reload",
    "preview_webview_set_muted",
    "preview_webview_set_zoom",
    "preview_webview_set_bounds",
    "preview_webview_create",
    "preview_webview_clear_data",
    "preview_webview_set_visibility",
    "preview_webview_diagnostics",
];

fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(APP_COMMANDS)),
    )
    .expect("failed to run tauri-build");
}
