// @generated by milim-control-contract. Do not edit by hand.

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export type ControlProtocolRangeV1 = { min: number, max: number, };

export type ControlCapabilitiesV1 = { timeline_sync: boolean, queued_turns: boolean, approvals: boolean, agents: boolean, workers: boolean, attachments: boolean, websocket_tickets: boolean, lan_discovery: boolean, push_notifications: boolean, inline_branches: boolean, appearance_assets: boolean, run_ledger?: boolean, run_inspection?: boolean, steering?: boolean, context_injection?: boolean, model_favorites?: boolean, thread_links?: boolean, };

export type ThreadLinkV1 = { owner_thread_id: string, target_thread_id: string, target_title: string, target_workspace: string | null, target_project: string | null, target_model: string | null, target_runtime: string, target_archived_at_ms: number | null, target_busy: boolean, target_queued_turns: number, created_at_ms: number, };

export type FrozenLinkedThreadGrantV1 = { target_thread_id: string, title: string, workspace: string | null, project: string | null, model: string | null, runtime: string, revision: number, epoch: string, max_timeline_seq: number, };

export type MailboxOriginV1 = { exchange_id: string, origin_thread_id: string, origin_title: string, origin_workspace: string | null, origin_project: string | null, };

export type ThreadSummaryV1 = { id: string, title: string, revision: number, epoch: string, updated_at_ms: number, archived_at_ms: number | null, model: string | null, reasoning_effort_overrides: { [key in string]?: string }, agent_id: string | null, workspace: string | null, busy: boolean, queued_turns: number, linked_threads: Array<ThreadLinkV1>, };

export type AgentSummaryV1 = { id: string, name: string, description: string, avatar: string, tool_mode: string, enabled_tool_count: number, skill_mode: string, enabled_skill_count: number, };

export type AgentSnapshotV1 = { id: string, name: string, description: string, avatar: string, system_prompt: string, tool_mode: string, enabled_tools: Array<string>, skill_mode: string, enabled_skills: Array<string>, };

export type ControlAttachmentV1 = { id: string, name: string, mime: string, size: number, content?: string, data_url?: string, truncated: boolean, };

export type GenerationSettingsV1 = { max_tokens: number | null, temperature: number | null, top_p: number | null, seed: number | null, stop: Array<string>, frequency_penalty: number | null, presence_penalty: number | null, top_k: number | null, min_p: number | null, repetition_penalty: number | null, thinking_token_budget: number | null, };

export type FrozenRunConfigV1 = { model: string, global_instructions: string, instructions: string, workspace: string | null, privacy: string, approval_mode: string, plan_mode: boolean, sandbox: boolean, computer_use: boolean, memory: boolean, delegation_policy: string, worker_model: string, agent: AgentSnapshotV1 | null, tool_mode: string, enabled_tools: Array<string>, skill_mode: string, enabled_skills: Array<string>, attachments: Array<ControlAttachmentV1>, native_session_id: string | null, native_session_cursor: string | null, reasoning_effort: string | null, generation: GenerationSettingsV1, adapter: string, linked_thread_grants: Array<FrozenLinkedThreadGrantV1>, claimed_mailbox_ids: Array<string>, };

export type RunCapabilitiesV1 = { ledger: boolean, inspectable: boolean, steering: boolean, visibility: string, };

export type RunSnapshotV1 = { id: string, thread_id: string, status: string, adapter: string, config: FrozenRunConfigV1, capabilities: RunCapabilitiesV1, created_at_ms: number, updated_at_ms: number, completed_at_ms: number | null, error: JsonValue | null, };

export type PendingApprovalV1 = { id: string, run_id: string, thread_id: string, kind: string, request: JsonValue, status: string, created_at_ms: number, };

export type QueuedTurnV1 = { id: string, thread_id: string, command_id: string, accepted_at_ms: number, display_text: string, attachments: Array<ControlAttachmentV1>, mailbox_origin?: MailboxOriginV1, };

export type PendingInputV1 = { id: string, thread_id: string, target_run_id: string | null, kind: string, state: string, created_at_ms: number, };

export type AppearanceColorsV1 = { primary_text: string, secondary_text: string, tertiary_text: string, placeholder_text: string, bg_primary: string, bg_secondary: string, bg_tertiary: string, sidebar_bg: string, accent: string, accent_light: string, border_primary: string, border_secondary: string, focus_border: string, success: string, warning: string, error: string, info: string, card_bg: string, card_border: string, input_bg: string, input_border: string, };

export type AppearanceGlassV1 = { enabled: boolean, blur_radius: number, opacity_primary: number, opacity_secondary: number, edge_light: string, };

export type AppearanceBackgroundV1 = { has_image: boolean, image_opacity: number, image_blur: number, overlay_color: string | null, overlay_opacity: number, fit: string, treatment: string, };

export type AppearanceBordersV1 = { card_radius: number, input_radius: number, border_opacity: number, };

export type AppearanceTypographyV1 = { font_family: string, mono_family: string, };

export type AppearanceSnapshotV1 = { revision: string, theme_id: string, name: string, is_dark: boolean, colors: AppearanceColorsV1, glass: AppearanceGlassV1, background: AppearanceBackgroundV1, borders: AppearanceBordersV1, typography: AppearanceTypographyV1, };

export type ControlBootstrapV1 = { protocol: ControlProtocolRangeV1, host_id: string, host_name: string, capabilities: ControlCapabilitiesV1, appearance: AppearanceSnapshotV1, threads: Array<ThreadSummaryV1>, models: Array<JsonValue>, favorite_model_ids: Array<string>, agents: Array<AgentSummaryV1>, active_runs: Array<RunSnapshotV1>, queued_turns: Array<QueuedTurnV1>, pending_inputs: Array<PendingInputV1>, pending_approvals: Array<PendingApprovalV1>, };

export type TimelineItemV1 = { id: string, thread_id: string, epoch: string, seq: number, run_id: string | null, type: string, data: JsonValue, created_at_ms: number, };

export type TimelinePageV1 = { thread_id: string, epoch: string, first_seq: number | null, last_seq: number | null, has_older: boolean, has_newer: boolean, before_seq: number | null, after_seq: number | null, items: Array<TimelineItemV1>, };

export type ControlEventV1 = { event_id: string, host_id: string, thread_id?: string, epoch?: string, seq?: number, type: string, data: JsonValue, };

export type ControlCommandStatusV1 = "applied" | "accepted" | "queued" | "needs_confirmation" | "conflict" | "failed";

export type ControlCommandKindV1 = "thread.create" | "thread.rename" | "thread.archive" | "thread.delete" | "thread.set_model" | "thread.set_agent" | "thread.link.add" | "thread.link.remove" | "message.delete" | "model_favorites.set" | "turn.send" | "turn.steer" | "context.inject" | "turn.inbox_delete" | "turn.stop" | "turn.regenerate" | "turn.queue_resume" | "turn.queue_move" | "turn.queue_delete" | "approval.resolve" | "worker.start" | "worker.continue_solo" | "worker.stop";

export type ControlCommandV1 = { command_id: string, kind: ControlCommandKindV1, thread_id?: string, expected_revision?: number, payload: JsonValue, confirmation_token?: string, };

export type ControlCommandResultV1 = { command_id: string, status: ControlCommandStatusV1, thread_id?: string, revision?: number, run_id?: string, queue_id?: string, confirmation_token?: string, message?: string, data: JsonValue, };

export type ResolvedRunCompositionV1 = { visibility: string, adapter: string, model: string, reasoning_effort: string | null, generation: GenerationSettingsV1, workspace: string | null, environment_policy: string, prompt_sections: Array<JsonValue>, tools: Array<JsonValue>, policies: JsonValue, attachments: Array<JsonValue>, };

export type RunEventV1 = { id: string, run_id: string, seq: number, step_id: string | null, type: string, data: JsonValue, created_at_ms: number, };

export type RunEventPageV1 = { run_id: string, after_seq: number | null, next_seq: number | null, has_more: boolean, events: Array<RunEventV1>, };

export type RunInspectionV1 = { run: RunSnapshotV1, composition: ResolvedRunCompositionV1 | null, };
