export const TRANSCRIPT_FADE_HEIGHT = 40;
export const DRAWER_EDGE_GESTURE_WIDTH = 28;
export const DRAWER_SWIPE_ACTIVATION_DISTANCE = 8;
export const DRAWER_SWIPE_COMMIT_DISTANCE = 52;
export const DRAWER_SWIPE_COMMIT_VELOCITY = 0.5;
