import {StyleSheet} from 'react-native';
import {type MobileTheme} from '../theme';

export function createMarkdownStyles(theme: MobileTheme) {
  const {fontFamily, monoFamily, palette} = theme;
  return {
    body: {color: palette.text, fontFamily, fontSize: 14.5, lineHeight: 22},
    code_inline: {color: palette.accent, backgroundColor: palette.raised, fontFamily: monoFamily},
    code_block: {color: palette.text, backgroundColor: palette.bg, borderColor: palette.border, fontFamily: monoFamily},
    fence: {color: palette.text, backgroundColor: palette.bg, borderColor: palette.border, fontFamily: monoFamily},
    link: {color: palette.accent},
  };
}

export function createStyles(theme: MobileTheme) {
  const {cardRadius, fontFamily, inputRadius, monoFamily, palette} = theme;
  return StyleSheet.create({
  appText: fontFamily ? {fontFamily} : {},
  root: {flex: 1, backgroundColor: palette.bg},
  app: {flex: 1, backgroundColor: 'transparent'},
  backgroundImage: {position: 'absolute', top: 0, right: 0, bottom: 0, left: 0},
  backgroundImageCover: {transform: [{scale: 1.06}]},
  backgroundDim: {backgroundColor: 'rgba(0,0,0,0.18)'},
  topbar: {height: 46, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: palette.sidebar, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: palette.border},
  topbarLeading: {flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 5},
  brandGroup: {minHeight: 38, flexShrink: 1, flexDirection: 'row', alignItems: 'center', gap: 8, marginLeft: -5, paddingHorizontal: 5, borderRadius: 8},
  brandMark: {width: 23, height: 23, resizeMode: 'contain'},
  brand: {color: palette.text, fontSize: 13.5, lineHeight: 15, fontWeight: '700', letterSpacing: -0.35},
  hostLabel: {color: palette.muted, fontSize: 9, lineHeight: 11, maxWidth: 210},
  connection: {height: 25, flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 8, borderRadius: 8, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.panel},
  connectionOnline: {borderColor: palette.borderStrong},
  connectionCount: {minWidth: 16, height: 16, marginRight: -4, paddingHorizontal: 4, borderRadius: 8, overflow: 'hidden', backgroundColor: palette.text, color: palette.accentInk, fontSize: 8.5, lineHeight: 16, fontWeight: '800', textAlign: 'center'},
  topbarDestinationActive: {backgroundColor: palette.raised},
  dot: {width: 6, height: 6, borderRadius: 3, backgroundColor: palette.muted},
  dotOnline: {backgroundColor: palette.success},
  connectionText: {color: palette.secondary, fontSize: 9, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.7},
  topbarActions: {flexDirection: 'row', alignItems: 'center', gap: 5},
  topbarButton: {width: 34, height: 34, borderRadius: 8, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: palette.border, backgroundColor: palette.panel},
  errorBanner: {paddingHorizontal: 16, paddingVertical: 9, backgroundColor: palette.dangerSurface, borderBottomWidth: 1, borderBottomColor: palette.dangerBorder, flexDirection: 'row', gap: 12, alignItems: 'center'},
  errorText: {color: palette.danger, fontSize: 12, flex: 1},
  retry: {color: palette.text, fontSize: 11, fontWeight: '700'},
  content: {flex: 1},
  screen: {flex: 1, paddingHorizontal: 12, paddingTop: 8},
  screenHeader: {height: 38, flexDirection: 'row', alignItems: 'baseline', gap: 8},
  screenSubtitle: {color: palette.muted, fontSize: 10.5},
  eyebrow: {color: palette.secondary, fontSize: 9.5, fontWeight: '700', letterSpacing: 1.5},
  screenTitle: {color: palette.text, fontSize: 20, lineHeight: 25, fontWeight: '700', letterSpacing: -0.55},
  input: {minHeight: 40, paddingHorizontal: 11, paddingVertical: 8, borderRadius: inputRadius, borderWidth: 1, borderColor: palette.borderStrong, backgroundColor: palette.input, color: palette.text, fontFamily, fontSize: 13.5},
  flex: {flex: 1},
  list: {flexGrow: 1, paddingBottom: 24, gap: 2},
  threadCard: {minHeight: 46, flexDirection: 'row', alignItems: 'center', backgroundColor: 'transparent', borderWidth: 1, borderColor: 'transparent', borderRadius: 8, paddingLeft: 10, paddingRight: 4, gap: 5},
  threadCardSelected: {backgroundColor: palette.panel, borderColor: palette.border},
  threadTopline: {flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 8},
  threadTitle: {color: palette.text, fontSize: 13.5, fontWeight: '600', flex: 1},
  threadOrigin: {color: palette.muted, fontSize: 9, fontWeight: '700', letterSpacing: 0.4, textTransform: 'uppercase'},
  queued: {color: palette.warning, fontSize: 9.5, fontWeight: '800'},
  threadMenu: {width: 38, height: 38, borderRadius: 7, alignItems: 'center', justifyContent: 'center'},
  drawerBackdrop: {flex: 1, flexDirection: 'row-reverse'},
  drawerDismiss: {flex: 1},
  drawer: {position: 'absolute', top: 0, bottom: 0, left: 0, borderRightWidth: 1, borderRightColor: palette.glassEdge, backgroundColor: palette.popover},
  drawerEdgeFade: {position: 'absolute', left: '100%', top: 0, bottom: 0, width: 96},
  drawerSafe: {flex: 1},
  drawerHeader: {minHeight: 72, flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 14, paddingTop: 5, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: palette.border},
  drawerHeading: {flex: 1, gap: 2},
  drawerTitleRow: {flexDirection: 'row', alignItems: 'center', gap: 7},
  drawerTitle: {color: palette.text, fontSize: 20, lineHeight: 24, fontWeight: '700', letterSpacing: -0.55},
  drawerCount: {minWidth: 21, height: 20, paddingHorizontal: 6, borderRadius: 7, overflow: 'hidden', backgroundColor: palette.raised, color: palette.secondary, fontSize: 10, lineHeight: 20, fontWeight: '800', textAlign: 'center'},
  drawerClose: {width: 38, height: 38, borderRadius: 8, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: palette.border, backgroundColor: palette.panel},
  markdownCode: {marginVertical: 6, borderWidth: 1, borderColor: palette.border, borderRadius: 6, backgroundColor: palette.bg, overflow: 'hidden'},
  markdownCodeHeader: {minHeight: 30, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, paddingLeft: 10, paddingRight: 6, borderBottomWidth: 1, borderBottomColor: palette.border},
  markdownCodeLanguage: {flex: 1, color: palette.muted, fontFamily: monoFamily, fontSize: 11},
  markdownCodeCopy: {minHeight: 28, flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 6},
  markdownCodeCopyText: {color: palette.muted, fontSize: 11, fontWeight: '600'},
  markdownCodeText: {margin: 0, padding: 10, borderWidth: 0, borderRadius: 0, backgroundColor: 'transparent'},
  transcriptImage: {width: '100%', maxHeight: 360, marginVertical: 6, borderRadius: cardRadius, backgroundColor: palette.raised},
  transcriptImageUnavailable: {marginVertical: 6, paddingVertical: 8, paddingHorizontal: 10, borderRadius: 6, borderWidth: 1, borderColor: palette.border, borderStyle: 'dashed'},
  transcriptImageUnavailableText: {color: palette.muted, fontSize: 12},
  imageViewer: {flex: 1, backgroundColor: '#000'},
  imageViewerContent: {flexGrow: 1, alignItems: 'center', justifyContent: 'center'},
  imageViewerBar: {position: 'absolute', top: 0, left: 0, right: 0, flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 12, paddingTop: 6},
  messagePressed: {opacity: 0.72},
  selectTextBody: {flexGrow: 0, maxHeight: 420, marginBottom: 8, borderRadius: inputRadius, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.input},
  selectTextContent: {padding: 12},
  selectTextValue: {color: palette.text, fontFamily, fontSize: 14, lineHeight: 21},
  drawerSearch: {minHeight: 38, flexDirection: 'row', alignItems: 'center', gap: 8, marginHorizontal: 12, marginTop: 10, paddingHorizontal: 10, borderRadius: inputRadius, borderWidth: 1, borderColor: palette.borderStrong, backgroundColor: palette.input},
  drawerSearchInput: {flex: 1, color: palette.text, fontFamily, fontSize: 13, paddingVertical: 7},
  unreadDot: {width: 7, height: 7, borderRadius: 3.5, backgroundColor: palette.accent},
  threadTitleUnread: {fontWeight: '700'},
  drawerCreateRow: {flexDirection: 'row', gap: 7, paddingHorizontal: 12, paddingTop: 11, paddingBottom: 8},
  drawerCreateButton: {width: 40, height: 40, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: palette.accent},
  drawerGroups: {flex: 1},
  drawerGroupList: {paddingHorizontal: 8, paddingTop: 2, paddingBottom: 20},
  drawerGroupSeparator: {height: 8},
  drawerGroup: {gap: 2},
  drawerGroupHeader: {minHeight: 48, flexDirection: 'row', alignItems: 'center'},
  drawerGroupToggle: {flex: 1, minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 7, paddingLeft: 6},
  drawerGroupIcon: {width: 27, height: 27, borderRadius: 7, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: palette.border, backgroundColor: palette.panel},
  drawerGroupBody: {flex: 1, minWidth: 0, gap: 1},
  drawerGroupTitle: {color: palette.text, fontSize: 12.5, fontWeight: '700'},
  drawerGroupSubtitle: {color: palette.muted, fontSize: 9.5},
  drawerGroupInfo: {width: 36, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: 7},
  drawerAttention: {minWidth: 18, height: 18, paddingHorizontal: 5, borderRadius: 6, overflow: 'hidden', backgroundColor: palette.accentSoft, color: palette.warning, fontSize: 9, lineHeight: 18, fontWeight: '800', textAlign: 'center'},
  drawerProjectDetails: {marginHorizontal: 7, marginBottom: 5, padding: 9, gap: 4, borderWidth: 1, borderColor: palette.border, borderRadius: 8, backgroundColor: palette.input},
  drawerProjectLabel: {color: palette.muted, fontSize: 8.5, fontWeight: '800', letterSpacing: 1.05},
  drawerProjectPath: {color: palette.secondary, fontSize: 10.5, lineHeight: 15},
  smallDanger: {color: palette.danger},
  button: {minHeight: 44, paddingHorizontal: 13, flexDirection: 'row', gap: 7, alignItems: 'center', justifyContent: 'center', borderRadius: 8, backgroundColor: palette.accent},
  buttonQuiet: {backgroundColor: palette.raised, borderWidth: 1, borderColor: palette.borderStrong},
  buttonDanger: {backgroundColor: palette.dangerSurface, borderWidth: 1, borderColor: palette.dangerBorder},
  buttonText: {color: palette.accentInk, fontSize: 12.5, fontWeight: '700'},
  buttonQuietText: {color: palette.text},
  buttonDangerText: {color: palette.danger},
  disabled: {opacity: 0.36},
  chatHeader: {minHeight: 42, flexDirection: 'row', alignItems: 'center', gap: 7, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: palette.border},
  back: {color: palette.secondary, fontSize: 12.5, fontWeight: '600'},
  chatTitle: {color: palette.text, fontSize: 14.5, fontWeight: '700', flex: 1},
  chatRunState: {flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 7, height: 24, borderRadius: 7, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.panel},
  chatRunText: {color: palette.muted, fontSize: 11, fontWeight: '800', letterSpacing: 0.5},
  chip: {maxWidth: '56%', flexShrink: 1, height: 29, flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: 'transparent', borderColor: palette.border, borderWidth: 1, borderRadius: 7, paddingHorizontal: 8},
  warningChip: {borderColor: palette.warning},
  chipText: {color: palette.secondary, fontSize: 10.5, fontWeight: '600'},
  pickerModal: {flex: 1, justifyContent: 'flex-end'},
  pickerSheet: {maxHeight: '88%', minHeight: '54%', paddingHorizontal: 12, paddingBottom: 8, borderTopLeftRadius: Math.max(16, cardRadius + 6), borderTopRightRadius: Math.max(16, cardRadius + 6), borderWidth: 1, borderBottomWidth: 0, borderColor: palette.glassEdge, backgroundColor: palette.popover, overflow: 'hidden'},
  pickerSheetCompact: {minHeight: 0, maxHeight: '50%'},
  sheetHandle: {width: 36, height: 4, borderRadius: 2, backgroundColor: palette.borderStrong, alignSelf: 'center', marginTop: 8, marginBottom: 10},
  pickerHeader: {flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 3, paddingBottom: 10},
  pickerTitle: {color: palette.text, fontSize: 18, fontWeight: '700', letterSpacing: -0.45},
  pickerSubtitle: {color: palette.muted, fontSize: 10.5, marginTop: 1},
  pickerClose: {width: 34, height: 34, borderRadius: 8, alignItems: 'center', justifyContent: 'center'},
  pickerSearch: {minHeight: 40, flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 10, borderRadius: 8, borderWidth: 1, borderColor: palette.borderStrong, backgroundColor: palette.input, marginBottom: 8},
  pickerSearchInput: {flex: 1, color: palette.text, fontFamily, fontSize: 13, paddingVertical: 7},
  pickerSearchClear: {width: 28, height: 28, alignItems: 'center', justifyContent: 'center'},
  pickerListView: {flexGrow: 1},
  pickerList: {flexGrow: 1, paddingBottom: 8, gap: 2},
  pickerGroupHeader: {minHeight: 34, flexDirection: 'row', alignItems: 'center', gap: 7, paddingHorizontal: 8, paddingTop: 4, paddingBottom: 2},
  pickerGroupTitle: {flex: 1, color: palette.muted, fontSize: 9, fontWeight: '800', letterSpacing: 1.2},
  pickerGroupCount: {color: palette.muted, fontSize: 10, fontWeight: '700'},
  pickerRow: {minHeight: 52, flexDirection: 'row', alignItems: 'center', gap: 3, paddingHorizontal: 5, paddingVertical: 3, borderRadius: 8, borderWidth: 1, borderColor: 'transparent', backgroundColor: 'transparent'},
  pickerRowSelected: {borderColor: palette.accentBorder, backgroundColor: palette.accentSoft},
  pickerRowMain: {flex: 1, minWidth: 0, minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 9, paddingHorizontal: 4},
  pickerRowIcon: {width: 24, height: 30, flexShrink: 0, alignItems: 'center', justifyContent: 'center'},
  pickerRowIconSelected: {borderColor: palette.accent},
  pickerRowBody: {flex: 1, minWidth: 0, gap: 3},
  pickerRowTopline: {flexDirection: 'row', alignItems: 'center', gap: 8},
  pickerRowTitle: {flex: 1, color: palette.text, fontSize: 13, fontWeight: '600'},
  pickerRowMeta: {flexDirection: 'row', alignItems: 'center', gap: 6, minHeight: 14},
  pickerRowRoute: {flex: 1, color: palette.muted, fontSize: 9.5, lineHeight: 14},
  pickerRowDescription: {color: palette.secondary, fontSize: 10.5, lineHeight: 15},
  capabilityRow: {flexDirection: 'row', alignItems: 'center', height: 14, gap: 4},
  pickerCapabilityIcon: {width: 14, height: 14, alignItems: 'center', justifyContent: 'center'},
  pickerCapabilityFastIcon: {transform: [{translateY: -1}]},
  capabilityTag: {color: palette.secondary, fontSize: 8, fontWeight: '800', letterSpacing: 0.6, paddingHorizontal: 5, paddingVertical: 2, borderRadius: 4, overflow: 'hidden', backgroundColor: palette.input, borderWidth: StyleSheet.hairlineWidth, borderColor: palette.border},
  pickerRowFavorite: {width: 38, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 7},
  pickerRowEffort: {minWidth: 36, height: 44, paddingHorizontal: 6, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4, borderRadius: 7},
  pickerRowEffortText: {color: palette.accent, fontSize: 9, fontWeight: '700'},
  reasoningEffortChoices: {marginLeft: 37, marginRight: 5, marginBottom: 3, paddingVertical: 6, gap: 5, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: palette.border},
  reasoningEffortLabel: {color: palette.muted, fontSize: 8.5, fontWeight: '800', letterSpacing: 0.8, textTransform: 'uppercase'},
  reasoningEffortScroll: {gap: 5, paddingRight: 8},
  reasoningEffortChoice: {minHeight: 38, minWidth: 48, paddingHorizontal: 10, alignItems: 'center', justifyContent: 'center', borderRadius: 7, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.input},
  reasoningEffortChoiceSelected: {borderColor: palette.accentBorder, backgroundColor: palette.accentSoft},
  reasoningEffortChoiceText: {color: palette.secondary, fontSize: 10.5, fontWeight: '700'},
  reasoningEffortChoiceTextSelected: {color: palette.accent},
  pickerFavoritesOnly: {minHeight: 46, flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 8, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: palette.border},
  pickerFavoritesOnlyText: {flex: 1, color: palette.secondary, fontSize: 11, fontWeight: '600'},
  pickerSwitch: {width: 34, height: 20, padding: 2, borderRadius: 10, justifyContent: 'center', backgroundColor: palette.raised, borderWidth: 1, borderColor: palette.borderStrong},
  pickerSwitchOn: {backgroundColor: palette.accentSoft, borderColor: palette.accent},
  pickerSwitchThumb: {width: 14, height: 14, borderRadius: 7, backgroundColor: palette.muted},
  pickerSwitchThumbOn: {alignSelf: 'flex-end', backgroundColor: palette.accent},
  chatBody: {flex: 1, marginHorizontal: -12, position: 'relative'},
  transcriptMask: {flex: 1},
  messageList: {flex: 1},
  messageContent: {flexGrow: 1, paddingHorizontal: 14, paddingTop: 12, paddingBottom: 18, gap: 12},
  historyControl: {minHeight: 44, alignSelf: 'center', flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, borderRadius: 8, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.panel},
  historyText: {color: palette.secondary, fontSize: 11, fontWeight: '600'},
  latestDock: {position: 'absolute', right: 0, left: 0, alignItems: 'center'},
  latestButton: {marginBottom: 8, minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 13, borderRadius: 9, borderWidth: 1, borderColor: palette.borderStrong, backgroundColor: palette.popover, shadowColor: '#000', shadowOpacity: 0.18, shadowRadius: 12, shadowOffset: {width: 0, height: 5}, elevation: 6},
  latestText: {color: palette.secondary, fontSize: 10.5, fontWeight: '700'},
  message: {borderRadius: 8, paddingHorizontal: 12, paddingVertical: 9, maxWidth: '82%'},
  userMessage: {backgroundColor: palette.accentSoft, borderWidth: 1, borderColor: palette.accentBorder, alignSelf: 'flex-end'},
  assistantMessage: {backgroundColor: 'transparent', alignSelf: 'stretch', maxWidth: '100%', paddingHorizontal: 2, paddingVertical: 4},
  messageRole: {color: palette.muted, fontSize: 10.5, fontWeight: '700', letterSpacing: 1, marginBottom: 5},
  modelChangeEvent: {alignSelf: 'stretch', minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 9, paddingVertical: 6},
  modelChangeLine: {flex: 1, height: StyleSheet.hairlineWidth, backgroundColor: palette.border},
  modelChangeCopy: {maxWidth: '76%', alignItems: 'center', gap: 2},
  modelChangeTopline: {flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5},
  modelChangePrimary: {color: palette.secondary, fontSize: 12, lineHeight: 17},
  modelChangeModel: {color: palette.text, fontWeight: '700'},
  modelChangeDetail: {color: palette.muted, fontSize: 10.5, lineHeight: 15, textAlign: 'center'},
  reasoningBlock: {paddingBottom: 7, marginBottom: 6},
  reasoningHeader: {minHeight: 28, flexDirection: 'row', alignItems: 'center', gap: 6},
  reasoningLabel: {color: palette.muted, fontSize: 10.5, fontWeight: '600'},
  reasoning: {color: palette.muted, fontSize: 11.5, lineHeight: 17, fontStyle: 'italic', paddingTop: 3},
  activityGroup: {alignSelf: 'stretch', borderTopWidth: StyleSheet.hairlineWidth, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: palette.border},
  activityGroupFailed: {borderColor: palette.dangerBorder},
  activitySummary: {minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 9, paddingHorizontal: 3, paddingVertical: 7},
  activitySummaryIcon: {width: 26, height: 26, flexShrink: 0, alignItems: 'center', justifyContent: 'center', borderRadius: 7, borderWidth: StyleSheet.hairlineWidth, borderColor: palette.border, backgroundColor: palette.panel},
  activitySummaryCopy: {flex: 1, minWidth: 0, gap: 2},
  activitySummaryLabel: {color: palette.text, fontSize: 13, lineHeight: 18, fontWeight: '600'},
  activitySummaryDetail: {color: palette.secondary, fontSize: 11.5, lineHeight: 16},
  activitySummaryStatus: {fontSize: 10.5, lineHeight: 15, fontWeight: '700'},
  activityRows: {paddingLeft: 17, paddingBottom: 8, borderLeftWidth: StyleSheet.hairlineWidth, borderLeftColor: palette.border, marginLeft: 16},
  runDetailsFooter: {gap: 5, paddingTop: 5, paddingRight: 4},
  runDetailsAction: {minHeight: 34, alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 4},
  runDetailsActionText: {color: palette.muted, fontSize: 10.5, fontWeight: '600'},
  runDetailsError: {color: palette.danger, fontSize: 10.5, lineHeight: 15, paddingRight: 8},
  runDetailsPanel: {gap: 2, paddingTop: 5, paddingRight: 4},
  runDetailSection: {borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: palette.border},
  runDetailSectionHeader: {minHeight: 38, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, paddingHorizontal: 4},
  runDetailSectionLabel: {color: palette.secondary, fontSize: 11, lineHeight: 16, fontWeight: '600'},
  runDetailJson: {color: palette.muted, fontFamily: monoFamily, fontSize: 10, lineHeight: 15, paddingHorizontal: 4, paddingBottom: 9},
  activityRow: {minHeight: 46, flexDirection: 'row', gap: 8, paddingVertical: 7, paddingRight: 3},
  activityRowIcon: {width: 22, height: 22, flexShrink: 0, alignItems: 'center', justifyContent: 'center'},
  activityRowBody: {flex: 1, minWidth: 0, gap: 3},
  activityRowTopline: {flexDirection: 'row', alignItems: 'flex-start', gap: 8},
  activityRowLabel: {flex: 1, color: palette.text, fontSize: 12.5, lineHeight: 17, fontWeight: '600'},
  activityRowStatus: {fontSize: 10.5, lineHeight: 16, fontWeight: '600'},
  activityDetailScroll: {minWidth: '100%', paddingRight: 14},
  activityRowDetail: {color: palette.muted, fontFamily: monoFamily, fontSize: 11, lineHeight: 16},
  diffChips: {flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 2},
  diffChip: {paddingHorizontal: 6, paddingVertical: 2, borderRadius: 5, overflow: 'hidden', fontFamily: monoFamily, fontSize: 10.5, fontWeight: '700'},
  diffChipAdded: {color: palette.success, backgroundColor: palette.raised},
  diffChipRemoved: {color: palette.danger, backgroundColor: palette.dangerSurface},
  activityNotice: {minHeight: 48, alignSelf: 'stretch', flexDirection: 'row', alignItems: 'center', gap: 9, paddingHorizontal: 4, paddingVertical: 8, borderTopWidth: StyleSheet.hairlineWidth, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: palette.border},
  missing: {color: palette.warning, fontSize: 12, paddingVertical: 6},
  attachments: {gap: 5, paddingTop: 6, paddingBottom: 2},
  attachment: {height: 27, maxWidth: 210, flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: palette.raised, borderWidth: 1, borderColor: palette.border, borderRadius: 7, paddingHorizontal: 7},
  attachmentText: {maxWidth: 155, color: palette.secondary, fontSize: 10},
  composerDock: {position: 'absolute', right: 12, bottom: 0, left: 12, overflow: 'hidden'},
  composerLayer: {position: 'absolute', top: 0, right: 0, left: 0, zIndex: 1, paddingTop: 5, paddingBottom: 3},
  composerLayerFront: {zIndex: 2},
  composer: {backgroundColor: 'transparent', borderWidth: 1, borderColor: palette.borderStrong, borderRadius: inputRadius, padding: 8},
  compactComposer: {minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 4, padding: 4, borderWidth: 1, borderColor: palette.borderStrong, borderRadius: inputRadius, backgroundColor: 'transparent'},
  compactComposerPrompt: {flex: 1, minHeight: 38, flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 10, borderRadius: Math.max(6, inputRadius - 3)},
  compactComposerText: {flex: 1, color: palette.placeholder, fontSize: 13, fontWeight: '500'},
  composerContextRow: {minHeight: 33, flexDirection: 'row', alignItems: 'center', gap: 6, paddingBottom: 5, marginBottom: 3, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: palette.border},
  composerInput: {color: palette.text, minHeight: 46, maxHeight: 126, paddingHorizontal: 2, paddingTop: 5, paddingBottom: 4, fontFamily, fontSize: 14, lineHeight: 20, textAlignVertical: 'top'},
  composerActions: {height: 44, flexDirection: 'row', alignItems: 'center', gap: 4},
  composerSpacer: {flex: 1},
  iconButton: {width: 44, height: 44, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: 'transparent'},
  iconButtonAccent: {backgroundColor: palette.accent},
  actionSheetList: {paddingBottom: 8, gap: 2},
  actionSheetButton: {minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 8, borderRadius: 8},
  actionSheetIcon: {width: 30, height: 30, alignItems: 'center', justifyContent: 'center'},
  actionSheetLabel: {color: palette.text, fontSize: 13.5, fontWeight: '600'},
  attentionCard: {backgroundColor: palette.panel, borderWidth: 1, borderColor: palette.border, borderRadius: cardRadius, padding: 14, gap: 10},
  inlineApprovalCard: {alignSelf: 'stretch', borderColor: palette.warning, backgroundColor: palette.input, borderRadius: Math.max(8, cardRadius - 2), padding: 12},
  attentionTitle: {color: palette.text, fontSize: 16, fontWeight: '600'},
  codeBlock: {color: palette.text, backgroundColor: palette.bg, borderRadius: inputRadius, padding: 10, fontFamily: monoFamily, fontSize: 12, maxHeight: 180},
  approvalDetailScroll: {minWidth: '100%'},
  actionRow: {flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center', gap: 8, flexWrap: 'wrap'},
  dialogBackdrop: {flex: 1, justifyContent: 'center', padding: 24, backgroundColor: 'rgba(0, 0, 0, 0.72)'},
  dialogCard: {gap: 14, padding: 18, borderRadius: cardRadius, borderWidth: 1, borderColor: palette.borderStrong, backgroundColor: palette.panel},
  hostList: {paddingBottom: 24, gap: 12},
  pageHeadingRow: {minHeight: 54, flexDirection: 'row', alignItems: 'center', gap: 4},
  pageHeadingCopy: {flex: 1, gap: 1},
  hostPairAction: {height: 34, flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 11, borderRadius: 8, borderWidth: 1, borderColor: palette.borderStrong, backgroundColor: palette.panel},
  hostPairActionText: {color: palette.secondary, fontSize: 11.5, fontWeight: '700'},
  hostPrimaryCard: {padding: 12, borderRadius: cardRadius, borderWidth: 1, borderColor: palette.focus, backgroundColor: palette.panel, gap: 11, shadowColor: '#000', shadowOpacity: 0.12, shadowRadius: 18, shadowOffset: {width: 0, height: 7}, elevation: 5},
  hostPrimaryTopline: {flexDirection: 'row', alignItems: 'center', gap: 9},
  hostMark: {width: 34, height: 34, resizeMode: 'contain'},
  hostPrimaryBody: {flex: 1, minWidth: 0, gap: 2},
  hostName: {color: palette.text, fontSize: 14, fontWeight: '700'},
  hostEndpoint: {color: palette.secondary, fontSize: 10.5},
  hostStatusPill: {height: 23, flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 7, borderRadius: 7, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.input},
  hostStatusPillOnline: {borderColor: palette.borderStrong},
  hostStatusText: {color: palette.secondary, fontSize: 8, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.55},
  hostMenu: {width: 32, height: 34, alignItems: 'center', justifyContent: 'center', borderRadius: 7},
  hostPrimaryFooter: {minHeight: 27, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, paddingTop: 9, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: palette.border},
  hostActivity: {color: palette.muted, fontSize: 10},
  hostCompatibility: {flexDirection: 'row', alignItems: 'center', gap: 5},
  hostCompatibilityText: {color: palette.secondary, fontSize: 9.5, fontWeight: '600'},
  hostSection: {gap: 6},
  hostSectionLabel: {color: palette.muted, fontSize: 8.5, fontWeight: '800', letterSpacing: 1.2, paddingHorizontal: 2},
  hostRows: {gap: 3},
  hostRow: {minHeight: 54, flexDirection: 'row', alignItems: 'center', gap: 9, paddingHorizontal: 10, borderRadius: 9, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.panel},
  hostRowMark: {width: 28, height: 28, resizeMode: 'contain'},
  hostRowBody: {flex: 1, minWidth: 0, gap: 2},
  hostRowTitle: {color: palette.text, fontSize: 12.5, fontWeight: '600'},
  hostRowMeta: {color: palette.muted, fontSize: 9.5},
  hostSwitchText: {color: palette.secondary, fontSize: 10, fontWeight: '700'},
  hostDisclosure: {minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 10, borderRadius: 9, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.panel},
  hostDisclosureIcon: {width: 30, height: 30, borderRadius: 7, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: palette.border, backgroundColor: palette.input},
  hostDisclosureBody: {flex: 1, minWidth: 0, gap: 2},
  hostDisclosureTitle: {color: palette.text, fontSize: 12.5, fontWeight: '600'},
  hostDisclosureCopy: {color: palette.muted, fontSize: 10, lineHeight: 14},
  hostManualForm: {gap: 9, paddingHorizontal: 9, paddingTop: 4, paddingBottom: 2},
  hostManualActions: {alignSelf: 'flex-end'},
  hostInfoRow: {minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 10, borderRadius: 9, borderWidth: StyleSheet.hairlineWidth, borderColor: palette.border, backgroundColor: palette.panel},
  hostDetails: {gap: 9, paddingBottom: 8},
  hostDetailBlock: {gap: 5, padding: 10, borderRadius: 8, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.input},
  hostDetailValue: {color: palette.secondary, fontSize: 11, lineHeight: 16},
  hostDetailGrid: {flexDirection: 'row', gap: 7},
  hostDetailStat: {flex: 1, minHeight: 58, gap: 5, padding: 9, borderRadius: 8, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.input},
  hostDetailStatValue: {color: palette.text, fontSize: 11, lineHeight: 15, fontWeight: '600'},
  section: {paddingVertical: 10, gap: 10},
  sectionTitle: {color: palette.text, fontSize: 16, fontWeight: '600'},
  help: {color: palette.muted, fontSize: 12.5, lineHeight: 18},
  empty: {flex: 1, minHeight: 180, paddingVertical: 38, paddingHorizontal: 16, alignItems: 'center', justifyContent: 'center', gap: 9},
  emptyTitle: {color: palette.text, fontSize: 17, fontWeight: '600'},
  emptyCopy: {maxWidth: 340, textAlign: 'center'},
  onboarding: {flex: 1, backgroundColor: palette.bg},
  onboardingTopbar: {height: 58, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: palette.sidebar, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: palette.border},
  onboardingBrand: {flexDirection: 'row', alignItems: 'center', gap: 9},
  onboardingMark: {width: 32, height: 32, resizeMode: 'contain'},
  onboardingWordmark: {color: palette.text, fontSize: 17, fontWeight: '700', letterSpacing: -0.55},
  mobileLabel: {color: palette.muted, fontSize: 9, fontWeight: '700', letterSpacing: 1.6},
  onboardingContent: {width: '100%', maxWidth: 520, alignSelf: 'center', paddingHorizontal: 20, paddingTop: 34, paddingBottom: 28, gap: 18},
  onboardingIntro: {gap: 9},
  heroTitle: {color: palette.text, fontSize: 34, lineHeight: 38, fontWeight: '700', letterSpacing: -1.5},
  heroCopy: {color: palette.secondary, fontSize: 14, lineHeight: 20},
  nearbyPanel: {gap: 9, padding: 13, borderRadius: cardRadius, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.panel},
  nearbyHeading: {minHeight: 36, flexDirection: 'row', alignItems: 'center', gap: 10},
  nearbyTitle: {color: palette.text, fontSize: 14.5, fontWeight: '600'},
  nearbySubtitle: {color: palette.muted, fontSize: 10.5, lineHeight: 15},
  nearbyRefresh: {width: 36, height: 36, alignItems: 'center', justifyContent: 'center', borderRadius: 8, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.raised},
  nearbyHost: {minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: 9, paddingHorizontal: 10, paddingVertical: 8, borderRadius: 9, borderWidth: 1, borderColor: palette.borderStrong, backgroundColor: palette.input},
  nearbyHostPending: {borderColor: palette.accent, backgroundColor: palette.raised},
  nearbyHostMark: {width: 30, height: 30, resizeMode: 'contain'},
  nearbyPairingSpinner: {width: 30, height: 30, alignItems: 'center', justifyContent: 'center'},
  nearbyHostBody: {flex: 1, minWidth: 0, gap: 2},
  nearbyHostName: {color: palette.text, fontSize: 12.5, fontWeight: '700'},
  nearbyHostEndpoint: {color: palette.muted, fontSize: 9.5},
  nearbyStatus: {flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 7, height: 24, borderRadius: 7, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.raised},
  nearbyStatusText: {color: palette.secondary, fontSize: 8, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.45},
  nearbyConnectAction: {flexDirection: 'row', alignItems: 'center', gap: 4, paddingLeft: 8},
  nearbyConnectText: {color: palette.text, fontSize: 10.5, fontWeight: '700'},
  nearbyEmpty: {color: palette.muted, fontSize: 11.5, lineHeight: 17},
  nearbyHelp: {color: palette.secondary, fontSize: 10.5, lineHeight: 15},
  manualPairToggle: {minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 13, paddingVertical: 10, borderRadius: cardRadius, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.panel},
  manualPairIcon: {width: 34, height: 34, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: palette.raised},
  manualPairTitle: {color: palette.text, fontSize: 13, fontWeight: '600'},
  manualPairCopy: {color: palette.muted, fontSize: 10.5, lineHeight: 14},
  pairingPanel: {gap: 10, padding: 15, borderRadius: cardRadius, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.panel},
  panelHeading: {flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 3},
  panelIcon: {width: 34, height: 34, borderRadius: 8, borderWidth: 1, borderColor: palette.borderStrong, backgroundColor: palette.raised, alignItems: 'center', justifyContent: 'center'},
  panelTitle: {color: palette.text, fontSize: 14.5, fontWeight: '600', marginBottom: 1},
  fieldLabel: {color: palette.muted, fontSize: 9, fontWeight: '700', letterSpacing: 1.2, marginTop: 2},
  pairActions: {flexDirection: 'row', justifyContent: 'flex-end', gap: 8, marginTop: 3},
  directNote: {flexDirection: 'row', alignItems: 'flex-start', gap: 9, paddingHorizontal: 2},
  directNoteText: {flex: 1, color: palette.muted, fontSize: 11.5, lineHeight: 17},
  claimInput: {minHeight: 78, textAlignVertical: 'top'},
  formError: {color: palette.danger, fontSize: 13, lineHeight: 18},
  scanner: {flex: 1, backgroundColor: '#000'},
  scannerOverlay: {flex: 1, justifyContent: 'space-between', alignItems: 'center', padding: 24},
  scannerTitle: {color: '#fff', fontSize: 19, fontWeight: '700', textShadowColor: '#000', textShadowRadius: 8},
  });
}
